### ISSUE TITLE
Adding a bunch of new websites.

### ISSUE THREAD

**Issue by Prajwal-Koirala** [sherlock-project/sherlock#760]
```json
	"YouTube (Username)": {
		"url": "https://www.youtube.com/user/{}",
		"errorType": "status_code"
	},
	"YouTube (Custom-URL)": {
		"url": "https://www.youtube.com/c/{}",
		"errorType": "status_code"
	},
```

The current format supports just the youtube username format and not the custom-url

**Comment by Prajwal-Koirala** [comment]
```
	"Imgur": {
		"url": "https://imgur.com/user/{}",
		"errorType": "status_code"
	},
```
Add imgur too

**Comment by Prajwal-Koirala** [comment]
```
	"Fotolog": {
		"url": "https://fotolog.com/author/{}",
		"errorType": "status_code"
	},
```
add Fotolog

**Comment by Prajwal-Koirala** [comment]
```
	"Pexels": {
		"url": "https://www.pexels.com/@{}",
		"errorType": "message",
		"errorMsg": "Ouch, something went wrong!"
	},
```

add Pexels

**Comment by Prajwal-Koirala** [comment]
```
	"Trip": {
		"url": "https://www.trip.skyscanner.com/user/{}",
		"errorType": "message",
		"errorMsg": "Page not found"
	},
```

**Comment by Prajwal-Koirala** [comment]
```
	"ColourLovers": {
		"url": "https://www.colourlovers.com/love/{}",
		"errorType": "message",
		"errorMsg": "Page Not Loved"
	},
```

**Comment by Prajwal-Koirala** [comment]
```
	"Codementor": {
		"url": "https://www.codementor.io/{}",
		"errorType": "status_code"
	},
```

**Comment by Prajwal-Koirala** [comment]
```
	"500px": {
		"url": "https://500px.com/{}",
		"errorType": "message",
		"errorMsg": "Sorry, no such page."
	},
```

**Comment by Prajwal-Koirala** [comment]
```
	"Canva": {
		"url": "https://www.canva.com/{}",
		"errorType": "message",
		"errorMsg": "Not found (404)"
	},
```

**Comment by Prajwal-Koirala** [comment]
```
	"AngelList": {
		"url": "https://angel.co/{}",
		"errorType": "message",
		"errorMsg": "We couldn't find what you were looking for."
	},
```

**Comment by Prajwal-Koirala** [comment]
@sdushantha

Let me know if i need to change something or add something before u close the issue.

**Comment by st0nkz** [comment]
There are attributes missing:

urlMain
username_claimed
username_unclaimed

Some of these also seem to report as found when the users are non-existent.

**Comment by Prajwal-Koirala** [comment]
well open source is open source for a reason.

someone will come and do more testing than me.

**Comment by st0nkz** [comment]
For now, I just tested 500px, which is one of the sites that report as found. However, all of them seem to be missing the attributes I stated above.

**Comment by Prajwal-Koirala** [comment]
> For now, I just tested 500px, which is one of the sites that report as found. However, all of them seem to be missing the attributes I stated above.

update the code for 500px should work now.

**Comment by bG9sIHVyIGhvbW8** [comment]
> > For now, I just tested 500px, which is one of the sites that report as found. However, all of them seem to be missing the attributes I stated above.
> 
> update the code for 500px should work now.

I had a look at the code and the attributes I stated above are still missing. They need to be specified so the site works as expected.

**Comment by sdushantha** [comment]
I am closing this issue as it is low effort.
